const form=document.querySelector('#fund-form'),holdings=document.querySelector('#holdings'),template=document.querySelector('#holding-template'),money=v=>Number(String(v??0).replaceAll(',','')),format=v=>money(v).toLocaleString('en-US'),moneyFields=['principal','yearStartNav','nav90','initialNav'];let editingId=new URLSearchParams(location.search).get('edit');
form.elements.nav.closest('label').style.display='none';moneyFields.forEach(key=>{form.elements[key].type='text';form.elements[key].inputMode='decimal'});
function calculate(){const rows=[...holdings.children],cost=rows.reduce((sum,row)=>sum+money(row.querySelector('[name=holdingCost]').value),0),stock=rows.reduce((sum,row)=>sum+money(row.querySelector('[name=holdingValue]').value),0),cash=money(form.elements.principal.value)-cost,nav=cash+stock,rate=base=>money(base)?(nav-money(base))/money(base)*100:0;form.elements.nav.value=nav;document.querySelector('#cash-output').textContent=format(cash);document.querySelector('#stock-output').textContent=format(stock);document.querySelector('#ytd-output').textContent=rate(form.elements.yearStartNav.value).toFixed(2)+'%';document.querySelector('#return90-output').textContent=rate(form.elements.nav90.value).toFixed(2)+'%';document.querySelector('#total-output').textContent=rate(form.elements.initialNav.value).toFixed(2)+'%';rows.forEach(row=>row.querySelector('.weight').textContent=`${cost?(money(row.querySelector('[name=holdingCost]').value)/cost*100).toFixed(2):'0.00'}%`);return nav}
function addHolding(item={}){const row=template.content.firstElementChild.cloneNode(true);row.querySelector('[name=holdingName]').value=item.name||'';row.querySelector('[name=holdingType]').value=item.type||'股票';row.querySelector('[name=holdingCost]').value=item.cost!==undefined?format(item.cost):'';row.querySelector('[name=holdingValue]').value=item.value!==undefined?format(item.value):'';row.querySelectorAll('input').forEach(input=>input.addEventListener('input',()=>{if(input.classList.contains('money'))input.value=format(input.value);calculate()}));row.querySelector('button').onclick=()=>{row.remove();calculate()};holdings.append(row)}
function fillForm(data){holdings.innerHTML='';Object.entries(data).forEach(([key,value])=>{if(form.elements[key]&&!Array.isArray(value))form.elements[key].value=moneyFields.includes(key)?format(value):value??''});(data.holdings||[]).forEach(addHolding);if(!holdings.children.length)addHolding();calculate()}
function payload(){const data=Object.fromEntries(new FormData(form));data.nav=calculate();data.holdings=[...holdings.children].map(row=>({name:row.querySelector('[name=holdingName]').value.trim(),type:row.querySelector('[name=holdingType]').value,cost:money(row.querySelector('[name=holdingCost]').value),value:money(row.querySelector('[name=holdingValue]').value)}));return data}
document.querySelector('#add-holding').onclick=()=>{addHolding();calculate()};moneyFields.forEach(key=>form.elements[key].addEventListener('input',()=>{form.elements[key].value=format(form.elements[key].value);calculate()}));
form.addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter||document.querySelector('.save'),data=payload(),url=editingId?`/api/snapshots/${editingId}`:'/api/snapshots',method=editingId?'PUT':'POST',result=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!result.ok){button.textContent='儲存失敗，請重試';return}button.textContent=editingId?'已覆寫 ✓':'已新增 ✓';editingId=null;history.replaceState({},'',location.pathname);setTimeout(()=>button.textContent='儲存並更新公開頁面 ↗',1200)});
(async()=>{const history=await fetch('/api/history').then(r=>r.json()).catch(()=>[]),selected=editingId?history.find(item=>String(item.id)===editingId):history[0];if(selected){fillForm(selected);if(editingId)document.querySelector('.save').textContent='覆寫此筆歷史紀錄'}else{form.elements.updatedAt.value=new Date().toISOString().slice(0,10);addHolding();calculate()}})();
